fix: Switch from the removed yaml.safeLoad to yaml.load (#244)
Solves the following error when using a YAML config file:

```
Parse options error: Cannot read config file: /app/.groovylintrc.yaml
Error: Function yaml.safeLoad is removed in js-yaml 4. Use yaml.load instead, which is now safe by default.
```

Co-authored-by: Ricky C <ricky.curtice@onerail.io>