fix: class not found request failure
Fix java.lang.NoClassDefFoundError during parseFile resulting in
the request failing and causing 500 status codes.

We now catch Throwable instead of Exception as this is best effort
anyway.

Fixes: nvuillam/vscode-groovy-lint#137